name: Fast action

# Configure the action trigger as you wish for your pipelines
on:
  push:
    branches: ['main', "master"]

jobs:
  # Add this job at your jobs block
  private_fast_action:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scipy xxhash
      - name: RUN FAST
        run: python script/prioritize.py > results.txt
      - name: Setup git
        run: |
          git config user.name "FAST ACTION"
          git config user.email "<>"
      - name: Commit
        run: |
          git add results.txt
          git commit -m "persisting test data"
          git push